name: Build Desktop

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - "packages/bytebotd/**"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
      # 1. Check out code
      - uses: actions/checkout@v4

      # 2. Enable QEMU so the amd64 runner can cross‑build arm64
      - uses: docker/setup-qemu-action@v3

      # 3. Set up Buildx builder
      - uses: docker/setup-buildx-action@v3

      # 4. Generate OCI labels + the single "edge" tag
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bytebot-ai/bytebot-desktop
          tags: type=edge

      # 5. Log in to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6. Build & push a multi‑arch image
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1 # hide "unknown/unknown" in GHCR
          DOCKER_BUILD_SUMMARY: false # keep logs concise
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: ./packages/
          file: ./packages/bytebotd/Dockerfile
          platforms: linux/amd64,linux/arm64 # build both archs in one go
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
